export const xrQuotes = [
  "WE HAVE A SHARED VISION OF CHANGE.",
  "Creating a world that is fit for the next 7 generations to live in.",
  "Our hearts tell us a different world is possible.",
  "Our vision of change is sufficiently broad that it can contain a variety of opinions on how best to work towards that change.",
  "A healthy, beautiful world, where individuality and creativity are supported, and where people work together, solving problems and finding meaning, with courage, power and love. This will be underpinned by cultures rooted in respect for nature, genuine freedoms and justice.",
  "WE SET OUR MISSION ON WHAT IS NECESSARY.",
  "Mobilising 3.5% of the population to achieve system change – such as momentum-driven organising.",
  "The change needed is huge and yet achievable.",
  "No regime in the 20th century managed to stand against an uprising which had the active participation of up to 3.5% of the population (watch Erica Chenoweth’s TEDx talk).",
  "We acknowledge that we are in the midst of a massive crisis, one which can be hard to comprehend and cope with. We are experiencing the 6th mass species extinction and we are not taking adequate steps to avert our civilisation from the most horrendous trajectory of climate change. ",
  "The world is deeply unequal, with wealth and power levers concentrated in a small minority. We have crises in our mental and physical health, including our children, based in different forms of malnutrition and an increasingly toxic environment. We live with the threat of pandemics alongside antibiotic failure. ",
  "Our financial system is destined for another crisis bigger than the last. There is a global culture of conquering others, of competition, of revenge and of terrorism.",
  "We recognise that our job may be less about saving the world and more about trying to develop our resilience as multiple collapses take places. We are focussed on significant change towards: A functioning democracy, where people have real agency in decision making. ",
  "This would include devolution of power to the level closest to people and communities, with structures to facilitate decision making locally, regionally, nationally and internationally, where appropriate.",
  "An economy designed to maximise well-being for all people and minimise harm to each other, our fellow creatures and our home planet. We need policies and laws that achieve greater equality, localised production, reduced consumption, zero carbon emissions and zero waste.",
  "Creating a regenerative culture. We can begin doing that right now!",
  "We can focus on symptoms of this toxic system, yet we also we take opportunities to point out that full system change is needed. ",
  "We also focus on the pillars that keep the current neo-liberal system in place: A debt and interest based, deregulated finance sector; A fake and decaying democracy; A media captured to the interests of exploitative rich people and corporations.",
  "WE NEED A REGENERATIVE CULTURE.",
  "Creating a culture which is healthy, resilient and adaptable.",
  "A regenerative human culture is healthy, resilient and adaptable; it cares for the planet and it cares for life in the awareness that this is the most effective way to create a thriving future for all of humanity. ",
  "Regenerative culture means improvements year on year, taking small steps to heal and improve, and on all levels, including individuals, communities, our soil, water and air. ",
  "More than being a network of activists, we seek to find ways of being and doing that support positive change. This can include ceremony and prayer (in ways that are neither dogmatic nor expected) as formats to find inspiration from things bigger than ourselves. We need to reconnect with our love for ourselves, our country and our people alongside wider neighbours; people and the natural world.",
  "Self care: how we take care of our own needs and personal recovery from this toxic system.",
  "Action care: how we take care of each other whilst we undertake direct actions and civil disobedience together.",
  "Interpersonal care: how we take care of the relationships we have, being mindful of how we affect each other, taking charge of our side of relationships.",
  "Community care – how we take care of our development as a network and community, strengthening our connections and adherence to these principles and values.",
  "People and Planet care – how we look after our wider communities and the earth that sustains us all.",
  "It’s about relationships. ",
  "Our relationships with ourselves and personal histories, our relationships with what we struggle against, our relationships with other individuals day to day, and our relationships as a group – these are completely interdependent. ",
  "Self care is also about taking care of the animal parts of the self that respond instinctively to stressful situations with fight or flight or faint.",
  "WE OPENLY CHALLENGE OURSELVES AND THIS TOXIC SYSTEM.",
  "Leaving our comfort zones to take action for change.",
  "We have a duty to disobey this system which destroys life on earth and is deeply unjust. ",
  "Some of us will undertake open (above ground*) actions that risk arrest and charges. ",
  "Evidence suggests that such open civil disobedience and direct action are crucial to change (See for example evidence in CounterPower by Tim Gee and This is an Uprising by Engler & Engler). ",
  "It isn’t necessary or required that everyone do this, as for some there are good reasons not to (we ask everyone to take time to be clear on their own circumstances, fears and motivations here). ",
  "Importantly, our Extinction Rebellion culture should support those of us willing to put ourselves on the line in this way – there are also many support roles that are useful and we need to enable at least 3% of the population to actively participate.",
  "We will practice a security culture to the extent that it enables actions to be planned without being intercepted before they are completed. ",
  "However our civil disobedience and direct actions are in full public light, organisers accept the risks they are taking, and we have issued a necessity statement online as to why we believe our actions are justified.",
  "However we are not just about being out there and taking action, we must also resource all aspects of a regenerative culture and also take time to reflect on whether what we are doing is effective. ",
  "We might find it challenging to keep a focus on some aspects of this work, including self-care and looking after each other. There can be a pull to do the next thing, to be active, but this can lead to burn-out.",
  "There is a value in us making changes in our own lives to reflect the changes needed, such as changing our diets, where we go on holiday and so on (however personal responsibility can be overstated and is based, to some extent, in privilege). For all of these challenges we ask for room, patience and willingness to try new things to see if they support our goals.",
  "We appreciate and admire those willing to take below ground or covert actions to fight for environment and social justice, within other settings.",
  "For clarity, and for the safety of those organising in Extinction Rebellion it is important we are clear that all actions taken in the name of Extinction Rebellion are above ground, i.e. that they are taken in the open and no below ground actions are taken as Extinction Rebellion.",
  "WE VALUE REFLECTING AND LEARNING.",
  "Following a cycle of action, reflection, learning, and planning for more action. Learning from other movements and contexts as well as our own experiences.",
  "We don’t know how things will change so we are willing to experiment and learn from what we do.",
  "Through ongoing questioning, reflection and learning about what has worked elsewhere we will improve what we do and not get stuck in repetitive behaviour.",
  "This is an active and ongoing process, requiring time and input for individuals and groups to think about what has gone well and why, what would be better to be done differently.",
  "WE WELCOME EVERYONE AND EVERY PART OF EVERYONE.",
  "Working actively to create safer and more accessible spaces.",
  "As a movement we are committed to campaigning for the right to life, and for the future life of our children and the planet. ",
  "We recognise that in order to change the world, we must change the way we think about and form relationships with those we work and ally ourselves with.",
  "The world is currently defined by multiple hierarchies of race, class, gender, sexuality, etc.",
  "For those lower down these hierarchies, much of the world isn’t a safe space.",
  "To create safer spaces we need to work actively to continuously build understandings of how these hierarchies operate, so that we can challenge them and build inclusion through making our spaces more accessible. Therefore, for our movement to be safe for everyone, it needs to be safe for the most marginalised.",
  "This principle includes a commitment to making safer spaces to support inclusivity.",
  "It is our goal that every individual is welcomed regardless of ethnicity, race, class, gender, gender identity, gender presentation, sexuality, age, income, ability, education, appearance, immigration status, belief or non-belief and activist experience.",
  "Every individual in the movement is responsible for creating and maintaining safer, compassionate and welcoming spaces.",
  "New people to the movement need to be explicitly welcomed. A simple starting point is adherence to these core principles.",
  "Physical violence or the incitement of violence towards others is not accepted.",
  "Discriminatory behaviour, language or behaviour that exhibits racial domination, sexism, anti-semitism, islamophobia, homophobia, ableism, class discrimination, prejudice around age and all other forms of oppression including abusive language towards others, either during an action or elsewhere, is not accepted whether physically or online.",
  "We also recognise that we are complex beings and exhibit many different parts of ourselves at different times and in different circumstances.",
  "For example, sometimes we might be caring, at other times judgemental, and at other times carelessly reactive.",
  "Some of those parts are parts of us that we’re happy to bring, and some of those parts are parts that we’re struggling with, or perhaps not even aware they existed until they revealed themselves.",
  "With this knowledge, we approach each other from a place of compassion, and encourage each other to increase our own self-awareness.",
  "WE ACTIVELY MITIGATE FOR POWER.",
  "Breaking down hierarchies of power for more equitable participation.",
  "The ground on which this network stands is on the relationships between its participants.",
  "We will work every day to build trust, respect and reciprocity among all of us.",
  "We assume all members to have good intentions and will react against disrespect.",
  "We use conflict resolution techniques to deal with conflict in a healthy way that will bring growth to our movement.",
  "We ground our work in dialogue, healing, collective transformation and justice.",
  "We won’t tolerate shaming of each other or bullying in any form.",
  "This requires us to be honest and clear with ourselves and each other; we all hold prejudices and biases, and these must be acknowledged rather than dwelled upon negatively.",
  "It is everyone’s responsibility to change destructive habits and behaviours.",
  "We recognise that our world as it stands is currently structured by various intersecting hierarchies based on class, race, gender, sexuality, (dis)ability and so on.",
  "As such each person’s experience is shaped by their position within these various social hierarchies.",
  "For instance, being a black woman one encounters different forms of oppression to a white woman, because of how race and gender combine and compound to shape experiences.",
  "Whilst we aim to live in a world where these hierarchies no longer exist, we cannot simply pretend that they don’t within our own network.",
  "For this reason we aim to centre voices that are normally the most marginalised, by allowing space for them to speak and encouraging those who normally wouldn’t to take leadership / coordination positions.",
  "This isn’t about deciding ‘who is the most oppressed’, it’s about consciously making space for the people who have to fight the most to be heard, recognised and respected.",
  "We weight coordinating roles towards marginalised groups.",
  "Our media messaging includes issues and voices that are normally ignored (e.g. the link between climate change and immigration detention centres). However we are mindful of not trying to speak on someone else’s behalf.",
  "Accessibility is important (in terms of child care, wheelchair access, not speaking in technical jargon), both for meetings and actions.",
  "We recognise that oppressive behaviours are socially embedded within us, and privileged people are asked to commit to questioning their privilege and to be open to being challenged.",
  "We refresh those who hold positions of responsibility so that power doesn’t get entrenched.",
  "We embed anti-oppressive practice into our training materials.",
  "Our strategy is focussed on doing the work it takes to forge genuine alliances with the grass roots movements of the people who are most marginalised.",
  "We also recognise that sometimes people make mistakes, misjudgements and missteps, and we seek to avoid humiliating exposure when it is clear that an issue needs to be raised and dealt with.",
  "Having a database, social media and a website; fundraising for meetings, etc, means that there is inevitably a centralisation of some power. To mitigate any power issues that can arise we have an Anchor Circle, whose role is transparent and into which there is a process for people to rotate in and out.",
  "Thinking about these questions is encouraged: If you always do a role, is it possible to train someone else to do it? If someone else is taking leadership on a role, can you learn from them so that you can step in? Can you challenge yourself to take on a more upfront role if this is something you don’t usually do? Do you take time to learn about power and privilege? Do you have an understanding of how the power and privilege you hold has an effect on other people and the movement you are part of?",
  "WE AVOID BLAMING AND SHAMING.",
  "We live in a toxic system, but no one individual is to blame.",
  "Blaming and shaming will not serve us in the long run. Whilst a specific campaign may seek to highlight the damaging role played by an institution, including individuals serving that institution, our starting point is that we live in toxic system that has damaged everybody. We can point out behaviour that is unhelpful, exploitative or abusive, and we won’t tolerate such behaviour, yet we don’t hand away our love or power by blaming and shaming. This is also true in our interpersonal and group dynamics as well as our relationship to ourselves.",
  "We embrace change that creates unity in diversity; we need to set right the relationships between us, avoiding the interpersonal traps that come from games we may inadvertently play and bringing awareness to the structures that would divide us. We accept that emotion sometimes needs to be expressed, that a period of venting can be necessary. We ask each other for good grace in how we share emotion and to return to a baseline of love, respect and conviviality. We need to be compassionate when mistakes are made. Mistakes are opportunities to learn. We look for ways to connect and understand. Listening deeply to each other is a powerful tool. We especially need to listen to those of us that come from groups whose voices tend to be silenced.",
  "WE ARE A NONVIOLENT NETWORK.",
  "Using nonviolent strategy and tactics as the most effective way to bring about change.",
  "Non-violence keeps our movement alive. We use non-violence to reveal the true perpetrators of systemic violence that people suffer from daily all over this world. It is our strategy to bring light to the injustice that too many suffer each day. We feel pain from the abuses of the police and others, and we will keep exposing their violence through our discipline. Non-violence has unequivocally been demonstrated to be an effective tool in mass mobilisations (see the work of Gene Sharp and Erica Chenoweth) and so we base a cornerstone of our movement on this.",
  "At the same time we also recognise that many people and movements in the world face death, displacement and abuse in defending what is theirs. We will not condemn those who justly defend their families and communities through the use of force, especially as we must also recognise that it is often our privilege which keeps us safe. We stand in solidarity with those whom have no such privilege to protect them and therefore must protect themselves through violent means; this does not mean we condone all violence, just that we understand in some cases it may be justified. Also we do not condemn other social and environmental movements that choose to damage property in order to protect themselves and nature, for example disabling a fracking rig or putting a detention centre out of action. Our network, however, will not undertake significant property damage because of risks to other participants by association.",
  "WE ARE BASED ON AUTONOMY AND DECENTRALISATION.",
  "We collectively create the structures we need to challenge power.",
  "We recognise that we can’t look to government to solve the world’s problems. It tends to concentrate power and wealth in the hands of a very privileged few, and often does not have the interests of the majority of people and the natural world at heart. We understand that we must self-organise to meet our own needs, which in the context of Extinction Rebellion means that we are working to equalise power by disrupting the usual pillars of power that govern our lives. In so doing, our intention is to create access to the resources we need, such as democratic structures that ensure everyone has a voice and an influence, information that comes without the bias of the rich and powerful, decent healthcare, education, social care and housing, clean energy production, and protections in law to prevent ecocide.",
  "Any person or group can organise autonomously around the issues that feel most pressing for them, and take action in the name and spirit of Extinction Rebellion – so long as the action fits within Extinction Rebellion’s principles and values. In this way, power is decentralised, meaning that there is no need to ask for permission from a central group or authority. We also promote the ideas of holocracy over consensus:",
  "That it may be agreed in a group for one or two people to do a specific task for the group. Those people are then fully empowered to do the task.",
  "They are best to seek advice and feedback but they don’t need anyone’s permission to complete the task.",
  "They are fully responsible for outcomes and should reflect on them and how to improve in future. If anything goes wrong they should help to clean up.",
  "At the same time, as a network, Extinction Rebellion self-organises to provide for the needs of the people participating within it, working to provide training in strategic action for change, educating ourselves and each other around issues of power, privilege and how to decolonise, creating better accessibility, caring for our emotional needs in relation to working together, and making time for connection and fun.",
];
