export const sunriseQuotes = [
  "For the air we breathe, for the water we drink, for the people we love, and the places we call home, we need a Green New Deal.",
  "THE GREEN NEW DEAL IS MORE THAN JUST ONE BILL.",
  "The Green New Deal means there is brightness ahead.",
  "Together we can win a world where work is fulfilling, where our water and air are clean and crisp, where the places we call home are here to stay, and the natural beauty of our earth is around for generations to come.",
  "WE ARE THE CLIMATE REVOLUTION",
  "Together, we will force the government to end the era of fossil fuel elites, invest in Black, brown and working class communities, and create millions of good union jobs.",
  "We’re on a mission to put everyday people back in charge and build a world that works for all of us, now and for generations to come.",
  "We are fighting for what science demands – government action that actually meets the scale, scope and urgency of the climate crisis. ",
  "WE’RE BUILDING PEOPLE POWER AND POLITICAL POWER. WE FIGHT FOR WHAT WE BELIEVE IN, NO MATTER WHAT",
  "We grow our power through organizing our communities.",
  "We are rooted in what we’re fighting for.",
  "We are all on a journey to become better organizers, leaders, and people.",
  "We rise to the challenge.",
  "We transform ourselves so our movement can win.",
  "We ask for help and give what we can.",
  "We respect each other and our shared home.",
  "We are a united movement.",
  "We oppose state violence with nonviolent action.",
  "We are in solidarity with other movements for change.",
  "We are full of determination, fire, and hope.",
];
